version: 0.1
log:
   fields
      service: registry
storage:
      cache:
         layerinfo: inmemory
      filesystem:
         rootdirectory: /var/lib/registry
http:
   addr: 0.0.0.0:5000

proxy:
      remoteurl: https://registry-2.docker.io

